#
# A simple Makefile to clean out build products.
# You can't build this program w/o the Mojave Compiler,
# in which case, you should be using cons, not make.
#

ROOT := ../../..

include $(ROOT)/mk/preface

clean::
	$(RM) *.cm* *.o *.p4* *.pp* *.exec
